kimm_lib/kimm_lib/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('book_manager/', include('book_manager.urls')),
    path('operator_manager/', include('operator_manager.urls')),
    path('accounts/', include('accounts.urls')),
    path('user_manager/',include('user_manager.urls')),
    path('book_rental/', include('book_rental.urls')),
    path('user_page/',include('user_page.urls')),
    path('reviews/',include('reviews.urls')),
]

kimm_lib/operator_manager/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib import admin
from operator_manager import views
from django.contrib.auth import views as auth_views #login用のview


urlpatterns = [
    #path('' , views.Index.as_view() , name = 'index'),
    url(r'^check_operator/(?P<pk>\d+)$' , views.CheckOperator.as_view() , name='check_operator'),
    url(r'^complete_operator/' , views.CompleteOperatorView.as_view() , name='complete_operator'),
    url(r'^operator_list/(?P<mode>\w+)/$' , views.OperatorListView.as_view() , name='operator_list'),
    url(r'^operator_list/$' , views.OperatorListView.as_view() , name='operator_list'),
    url(r'^operator_detail/(?P<pk>\d+)$' , views.OperatorDetailView.as_view() , name='operator_detail'),
]
urlpatterns += [
    url(r'^operator_create/$' , views.OperatorCreateView.as_view() , name='operator_create'),
    url(r'^operator_edit/(?P<pk>\d+)/$' , views.OperatorEditView.as_view() , name='operator_edit'),
    
]

kimm_lib/reviews/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib import admin
from reviews import views
from django.contrib.auth import views as auth_views #login用のview


urlpatterns = [
    path('book_review/<int:pk>' , views.book_review , name = 'book_review'),
]

kimm_lib/book_manager/models.py
from django.db import models
from django.core.validators import *
# Create your models here.

class Category(models.Model):
    code = models.CharField(max_length=2, unique=True)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.code + self.name
 
class BookInfo(models.Model):
    isbn = models.CharField(max_length=20, unique=True)
    title = models.CharField(max_length=150)
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    author = models.CharField(max_length=50, null=True)
    publisher = models.CharField(max_length=50, null=True)
    publish_date = models.DateField(null=True)
    delete_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.title + str(self.category) + self.author + self.publisher  

class Book(models.Model):
    bookinfo = models.ForeignKey(BookInfo, on_delete=models.PROTECT)
    arrival_date = models.DateField(null=True)
    disposal_date = models.DateField(null=True, blank=True)
    remarks = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.bookinfo + self.arrival_date + self.disposal_date + self.remarks

kimm_lib/operator_manager/models.py
from django.db import models

# Create your models here.

kimm_lib/operator_manager/models/operator.py
from django.db import models
from django.core.validators import *
from operator_manager.models.position import Position
# Create your models here.

class Operator(models.Model):
    email = models.EmailField(max_length=100, unique=True)
    full_name = models.CharField(max_length=50)
    password = models.CharField(max_length=32)
    birthday = models.DateField()
    position = models.ForeignKey(Position, on_delete=models.PROTECT)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    def __str__(self):
        return self.full_name + " " + self.email

kimm_lib/operator_manager/forms/search_form3.py
from django import forms
from operator_manager.models import Operator
from django.contrib.auth.models import User
from django.core.validators import *


CHOICES3 = [
    ('id', 'ID'),
    ('name', '名前'),
    ('position', '役職'),
]

class SearchForm3(forms.Form):
    type = forms.ChoiceField(label='', required=True, choices=CHOICES3)
    find = forms.CharField(label='', required=True, widget=forms.TextInput())

kimm_lib/operator_manager/views.py
from django.shortcuts import render

# Create your views here.

kimm_lib/operator_manager/views/check_operator_views.py
from django.shortcuts import render ,  redirect
from django.http import HttpResponse , HttpRequest
from django.views.generic import TemplateView ,ListView, DetailView, CreateView, UpdateView, DeleteView

# from operator_manager.forms. import *
from operator_manager.models.operator import Operator
from operator_manager.models.position import Position

from django.db.models import *
from django.contrib import messages
from django.urls import reverse_lazy
from django.core.paginator import Paginator
from django.forms.models import model_to_dict
from accounts.views.usercheck import usercheck
from accounts.views.operatorcheck import operatorcheck
from accounts.views.check import check
from accounts.views.admincheck import admincheck


import datetime

class CheckOperator(DetailView):
    template_name ='operator_manager/check_operator.html'
    model = Operator

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     id = self.kwargs['pk']
    #     operator = Operator.objects.get(id = id)
    #     return context

    def get(self, request,  *args, **kwargs):
        #アドミンチェック
        c = admincheck(request)
        if c is not None:
            return c

        # 結合時にsession['id']に変更
        if request.session['id'] == int(self.kwargs['pk']):
            messages.success(self.request, 'ログインユーザ自身を削除することはできません')
            return redirect(self.request.META['HTTP_REFERER'])
        else :
            id = self.kwargs['pk']
            operator = Operator.objects.get(id = id)
            context = {
                'object' : operator,
            }
            return render(request,'operator_manager/check_operator.html',context)

    def post(self, request, *args, **kwargs):
        operator = Operator.objects.get(id = self.kwargs['pk'])
        operator.is_active = False
        operator.save()
        return redirect(to ='/operator_manager/complete_operator')

kimm_lib/operator_manager/views/complate_operator_views.py
from django.shortcuts import render ,  redirect
from django.http import HttpResponse , HttpRequest
from django.views.generic import TemplateView ,ListView, DetailView, CreateView, UpdateView, DeleteView

# from operator_manager.forms. import *
from operator_manager.models.operator import Operator
from operator_manager.models.position import Position

from django.db.models import *
from django.contrib import messages
from django.urls import reverse_lazy
from django.core.paginator import Paginator
from django.forms.models import model_to_dict
from accounts.views.usercheck import usercheck
from accounts.views.operatorcheck import operatorcheck
from accounts.views.check import check
from accounts.views.admincheck import admincheck


import datetime

class CompleteOperatorView(TemplateView):
    model = Operator
    template_name ='operator_manager/complate_operator.html'

    def get(self, request, **kwargs):
        #アドミンチェック
        c = admincheck(request)
        if c is not None:
            return c

        return super().get(self, request, **kwargs)

kimm_lib/operator_manager/views/operator_create.py
from django.shortcuts import render ,  redirect
from django.http import HttpResponse , HttpRequest
from django.views.generic import TemplateView ,ListView, DetailView, CreateView, UpdateView, DeleteView

from operator_manager.forms.operator_form import Operator_Form
from operator_manager.models.operator import Operator
from operator_manager.models.operator import Position

from django.db.models import *
from django.contrib import messages
from django.urls import reverse_lazy
from django.core.paginator import Paginator
from django.forms.models import model_to_dict
from accounts.views.usercheck import usercheck
from accounts.views.operatorcheck import operatorcheck
from accounts.views.check import check
from accounts.views.admincheck import admincheck

class OperatorCreateView(CreateView):
    template_name ='operator_manager/operator_create.html'
    model = Operator
    form_class = Operator_Form
    success_url=reverse_lazy('operator_list', kwargs={'mode':'all'})

    """
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['isbn'] = self.request.session['isbn']
        context['form'] = Operator_Form(initial={'isbn' : context['isbn']})
        print(context)
        return context
    """
    def form_valid(self, form):
        password = form.cleaned_data.get('password')
        password_check= form.cleaned_data.get('password_check')
        if password == password_check:
            result = super().form_valid(form)
            messages.success(
                self.request, 'オペレータユーザupdate成功です')
            return result
        else:
            result = super().form_invalid(form)
            messages.warning(
                self.request,'パスワードチェックしてください！'
                )
            return result

    def get(self, request, **kwargs):
        #アドミンチェック
        c = admincheck(request)
        if c is not None:
            return c

        return super().get(self, request, **kwargs)

kimm_lib/operator_manager/views/operator_detail_view.py
from django.shortcuts import render ,  redirect
from django.http import HttpResponse , HttpRequest
from django.views.generic import TemplateView ,ListView, DetailView, CreateView, UpdateView, DeleteView

from operator_manager.models.operator import Operator
from operator_manager.models.position import Position
# from operator_manager.forms import *

from django.db.models import *
from django.contrib import messages
from django.urls import reverse_lazy
from django.core.paginator import Paginator
from django.forms.models import model_to_dict
from accounts.views.usercheck import usercheck
from accounts.views.operatorcheck import operatorcheck
from accounts.views.check import check
from accounts.views.admincheck import admincheck

#オペレータ一覧・検索
class OperatorDetailView(DetailView):
    model = Operator
    template_name = 'operator_manager/operator_detail.html'

    def get(self, request, **kwargs):
        #アドミンチェック
        c = admincheck(request)
        if c is not None:
            return c

        return super().get(self, request, **kwargs)

kimm_lib/operator_manager/views/operator_edit.py
from django.shortcuts import render ,  redirect
from django.http import HttpResponse , HttpRequest
from django.views.generic import TemplateView ,ListView, DetailView, CreateView, UpdateView, DeleteView

from operator_manager.forms.operator_form import Operator_Form
from operator_manager.models.operator import Operator
from operator_manager.models.operator import Position

from django.db.models import *
from django.contrib import messages
from django.urls import reverse_lazy
from django.core.paginator import Paginator
from django.forms.models import model_to_dict
from django.contrib.messages.views import SuccessMessageMixin
from accounts.views.usercheck import usercheck
from accounts.views.operatorcheck import operatorcheck
from accounts.views.check import check
from accounts.views.admincheck import admincheck
from django import forms

class OperatorEditView(UpdateView):
    template_name ='operator_manager/operator_create.html'
    model = Operator
    form_class = Operator_Form
    success_url=reverse_lazy('operator_list')

    # def get(self, request,  *args, **kwargs):
    #     # 結合時にsession['id']に変更
    #     if request.session['id'] == int(self.kwargs['pk']):
    #         messages.success(self.request, 'ログインユーザ自身を編集することはできません')
    #         return redirect(self.request.META['HTTP_REFERER'])
    #     else :
    #         return UpdateView.get(self, request, *args, **kwargs)
    #         # id = self.kwargs['pk']
    #         # operator = Operator.objects.get(id = id)
    #         # form = Operator_Form(instance = operator)
    #         # context = {
    #         #     'object' : operator,
    #         #     'form' : form,
    #         # }
    #         # return render(request,'operator_manager/operator_create.html',context)


    def form_valid(self, form):
        password = form.cleaned_data.get('password')
        password_check= form.cleaned_data.get('password_check')
        if password == password_check:
            result = super().form_valid(form)
            messages.success(
                self.request, 'オペレータユーザupdate成功です')
            del self.request.session['samePerson']
            return result
        else:
            result = super().form_invalid(form)
            messages.warning(
                self.request,'パスワードチェックしてください！'
                )
            return result
        
    def get(self, request , *args , **kwargs):
        c = admincheck(request)
        if c is not None:
            return c
        if request.session['id'] == int(self.kwargs['pk']):
            request.session['samePerson'] = True
            return super().get(self, request, **kwargs)
        else:
            request.session['samePerson'] = False
            return super().get(self, request, **kwargs)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.session['samePerson']:
            context['form'].fields['is_admin'].widget = forms.HiddenInput()
        return context
        
        
        

        

kimm_lib/operator_manager/views/operator_list_view.py
from django.shortcuts import render ,  redirect
from django.http import HttpResponse , HttpRequest
from django.views.generic import TemplateView ,ListView, DetailView, CreateView, UpdateView, DeleteView

from operator_manager.models.operator import Operator
from operator_manager.models.position import Position
from operator_manager.forms import *

from django.db.models import *
from django.contrib import messages
from django.urls import reverse_lazy
from django.core.paginator import Paginator
from django.forms.models import model_to_dict
from accounts.views.usercheck import usercheck
from accounts.views.operatorcheck import operatorcheck
from accounts.views.check import check
from accounts.views.admincheck import admincheck

#オペレータ一覧・検索
class OperatorListView(ListView):
    model = Operator
    template_name = 'operator_manager/operator_list.html'
    paginate_by = 10

    #postでの処理
    def post(self , request, mode=None):
        if (request.method == 'POST'):
            request.session['form_value3'] = self.request.POST['find']
            request.session['type3'] = self.request.POST['type']
            return self.get(request, mode)

    #formをつくる(ページネーションしても情報維持)
    def get_context_data(self):
        context = super().get_context_data()
        form = SearchForm3()
        context['form'] = form
        if 'form_value3' in self.request.session:
            find = self.request.session['form_value3']
            type = self.request.session['type3']
            context['form'] = SearchForm3(initial = {'find': find, 'type': type})
            #typeに応じた文字表示の分岐
            if type == 'id':
                context['word'] =  'ID：「' + str(self.request.session['form_value3']) + '」の検索結果'
            elif type == 'name':
                context['word'] =  '名前：「' + str(self.request.session['form_value3']) + '」の検索結果'
            elif type == 'position':
                context['word'] =  '資料タイトル：「' + str(self.request.session['form_value3']) + '」の検索結果'

        else:
            context['word'] = '全件一覧'
        return context

    #listの獲得
    def get_queryset(self):
        if 'form_value3' in self.request.session:
            find = self.request.session['form_value3']
            type = self.request.session['type3']

            if find is not None:
                #typeに応じた検索結果の分岐
                if type == 'id':
                    #数字（半角・全角）であるか判断
                    if str.isnumeric(find) == False:
                        return Operator.objects.none().order_by('id')
                    else:
                        return Operator.objects.filter(Q(pk=int(find))&Q(is_active=True)).order_by('id')
                elif type == 'name':
                    return Operator.objects.filter(Q(full_name__icontains=find)&Q(is_active=True)).order_by('id')
                elif type == 'position':
                    return Operator.objects.filter(Q(position__name__icontains=find)&Q(is_active=True)).order_by('id')
            else:
                return Operator.objects.all().order_by('id')
        else:
            return Operator.objects.filter(Q(is_active=True)).order_by('id')

    #modeによる分岐（mode=allの場合session[form_value3]を破棄)
    def get(self, request, mode=None):
        #アドミンチェック
        c = admincheck(request)
        if c is not None:
            return c

        if mode == 'all':
            if 'form_value3' in self.request.session:
                del self.request.session['form_value3']
                del self.request.session['type3']
        return super().get(self, request)

kimm_lib/operator_manager/templates/operator_manager/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- bootstraop css-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- google font -->
    <link href="https://fonts.googleapis.com/css?family=Sawarabi+Gothic" rel="stylesheet">
    <title>{{title}}</title>
    <style>
        *{
            font-family: "Sawarabi Gothic";
            margin: 0;
            padding: 0;

        }
        body{
            background-color:#F5F5F5;
            text-align: center;

        }
        a , u{
            text-decoration: none !important;
            color: black;
        }
        .login_container{
            margin-top: 10px;
            height: 25px;
            width: 100%;
        }
        .login_user{
            font-size: 25px;
            float: right;
            margin-right: 3em;
        }
        #base_title{
            font-size: 3em;
            margin-top: 15px;
            text-align: center;
            height: 95px;
            width: 100%;
        }

        .manager{
            font-size: 25px;
        }
        .base_img img{
            width: 250px;
            height: 350px;
        }

        .create{
    width: 100%;
    height: 1000px;
}
.createbox{
    margin: auto;
}
    </style>
</head>
<body>
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

<div class="login_container">
    <span class="login_user">ようこそ！管理者様</span>
</div>

<div class="contatiner">

        <div>

            <div id="base_title">
                    図書管理システム
            </div>
        </div>

        <hr>
        <div class="row">
                <div class="col manager"><a href="#">会員管理</a></div>
                <div class="col manager"><a href="{% url 'isbnsearch' %}">資料追加</a></div>
                <div class="col manager"><a href="{% url 'bookinfo_list' 'all' %}">資料目録検索</a></div>
                <div class="col manager"><a href="{% url 'book_list' 'all' %}">資料台帳検索</a></div>
              </div>
</div>

{% if messages %}
  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="messages mt-3">
          {% for message in messages %}
            <div class="alert alert-dismissable alert-{{ message.tag }}" data-alert="alert">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              {{ message }}
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
{% endif %}


{% block content %}


{% endblock %}


</body>



<script type="text/javascript">
{% block javascript %}

{% endblock %}
</script>








</html>

kimm_lib/operator_manager/templates/operator_manager/check_operator.html
{% extends 'book_manager/base.html' %}

{% block content %}
<br>
<h1>オペレータ{{object.name}}の削除</h1>
<table style="width:70%;">
  <tr>
    <th>ID</th>
    <th>オペレータユーザ名</th><th>E-mail</th><th>生年月日</th><th>役職</th>
    <tr>
    <td>{{ object.id }}</td><td>{{ object.full_name }}</td>
    <td>{{ object.email }}</td><td>{{ object.birthday }}</td><td>{{ object.position }}</td>
    </tr>
</table>

<br>
<form method="post">
    {% csrf_token %}
      <div class="container">
        <div class="col-12">
          <a class="btn btn-info" href="{% url 'operator_list' 'all' %}" style="color: white;">戻る</a>
          <button class="btn btn-danger" id="save" type = "submit">削除</button>
          
        </div>
      </div>
</form>
{% endblock %}

kimm_lib/operator_manager/templates/operator_manager/complate_operator.html
{% extends 'book_manager/base.html' %}

{% block content %}

<h1>削除が完了しました</h1>
<a class="btn btn-info" href="{% url 'operator_list' 'all' %}">リストに戻る</a>


{% endblock %}

kimm_lib/operator_manager/templates/operator_manager/operator_create.html
{% extends 'book_manager/base.html' %}

{% block meta_title %}
  {% if object.pk %}
    {{ object.title }}
    {% else %}
    POST
    {% endif %}
  {% endblock %}
{% block page_title %}
  {% if object.pk %}
    {{ object.title }}
  {% else %}
    POST
  {% endif %}
{% endblock %}

<br>
<br>
<br>
{% block content %}
<form method="post">
  {% csrf_token %}
      <div style="width: 100%; height :200px;">
          <div class="row" id="textbody" style="width:25%;margin: 20px auto;" >
              
                  
              <table>
                  <div class="col-12">

                  {{ form.as_table}}
                  
                  
                  </div>
              </table>
          </div>

      </div>
                     
     <br>
     <br>
     <br>
     <br>
     <br>
     <br>
     <br>
     
    <div class="container">
      <div class="col-12">
        <input type="button" value="戻る" onClick="javascript:history.go(-1);">
        <button class="btn btn-primary" id="save">登録する</button>
      </div>
    </div>
  
  
</form>


{% endblock %}

kimm_lib/operator_manager/templates/operator_manager/operator_detail.html
{% extends 'book_manager/base.html' %}

{% block content %}
<a href="{% url 'operator_edit' object.pk %}" class="btn btn-success"   style='color:white;'>編集</a>   
<a href="{% url 'check_operator' object.pk %}" class="btn btn-danger" style='color:white;'>削除</a>
<br>
<br>
<h2>【オペレータユーザ情報詳細】</h2>
<div class="">
        <h2>ID：{{ object.id }}</h2>
      </div>
      <table class="table table-hover"    style="width:60%;margin: 0 auto; background-color: white;">

        <tr>
          <th scope="col">名前</th>
          <td>{{ object.full_name }}</td>
        </tr>

        <tr>
          <th scope="col">e-mail</th>
          <td>{{ object.email }}</td>
        </tr>
        <tr>
          <th scope="col">生年月日</th>
          <td>{{ object.birthday }}</td>
        </tr>

        <tr>
          <th scope="col">役職</th>
          <td>{{ object.position }}</td>
        </tr>

      </table>
      <br>
      <hr>
      <input type="button" value="会員一覧へ戻る" onClick="javascript:history.go(-1);">




{% endblock %}

kimm_lib/operator_manager/templates/operator_manager/operator_list.html
{% extends 'book_manager/base.html' %}

{% block content %}
<a style="color: white;" href="{% url 'operator_create' %}" class="btn btn-primary">オペレータユーザ登録</a>
<br>
<hr>
<br>
<h2>【オペレータ検索】</h2>
<br>
<form class="" action="{% url 'operator_list' 'search' %}" method="post">
{% csrf_token %}
{{ form }}
<input type="submit" name="" value="検索">
</form>
<br>
{{ word }}
<br>
{% if object_list|length == 0 %}
<p style="color:red;">※何も見つかりませんでした</p>
{% endif %}
<br>

<table class="table table-hover" style="width: 80%; margin: 0 auto;" >
        <tr>
          <th scope="col">ID</th>
          <th scope="col">名前</th>
          <th scope="col" >誕生日</th>
          <th scope="col">役職</th>
          <th scope="col"></th>
          <th scope="col"></th>
        </tr>
        {% for obj in object_list %}
          <tr>
            <td>{{ obj.id }}</td>
            <td><a style='color:blue;' href="{% url 'operator_detail' obj.pk %}">{{ obj.full_name }}</a></td>
            <td>{{ obj.birthday}}</td>
            <td>{{ obj.position}}</td>
            <td><a class="btn btn-info"  style='color:white;' href="{% url 'operator_edit' obj.pk %}">編集</a></td>
            <td><a class="btn btn-danger" style='color:white;' href="{% url 'check_operator' obj.pk %}">削除</a> </td>
        </tr>
        {% endfor %}

</table>


<!--ページネーション-->
<div class="pagination" style="">
    <ul class="pagination" style="margin: 0 auto; margin-top:10px;">
        <!-- 前へ の部分 -->
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% else %}
            <li class="page-item">
                <a class="page-link" href="#" style="color:black;">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% endif %}

        <!-- 数字の部分 -->
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <li class="page-item active"><a class="page-link" href="#!">{{ num }}</a></li>
            {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
            {% endif %}
        {% endfor %}

        <!-- 次へ の部分 -->
        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        {% else %}
            <li class="page-item">
                <a class="page-link" href="#" style="color:black;">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        {% endif %}
    </ul>
</div>


<br>
<hr>
<a class="btn btn-dark" style="color:white;" href="{% url 'operator_list' 'all' %}">全件一覧へ</a>

{% endblock %}